#include <iostream>
#include <algorithm>
#include <unordered_map>

using namespace std;

int main(){
    int t;
    cin >> t;
    for(int a0 = 0; a0 < t; a0++){
        long n;
        cin >> n;
        long long int f1 = 1,f2 = 2,f = 0, sum = 0;
        while(f1 < n)
        {
            if(f1 % 2 == 0)
            {
                sum += f1;
            }
            f = f1 + f2;
            f1 = f2;
            f2 = f;
            
        }
        cout << sum << endl;
    }   return 0;
}

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
// the first 10 terms will be:
// 1,1,2,3,5,8,13,21,34,55,89,...
//By considering the terms in the Fibonacci sequence whose values do not exceed , find the sum of the even-valued terms.
